"""Weekly best-bet card: the live orchestration entry point.

For every game of an upcoming week it prints the model's view and the single
best bet, tiered STRONG / LEAN / PASS. Designed to be run any time; it
refreshes the dataset (lines update upstream several times a day), replays
history to get current ratings, and evaluates the posted lines.

Run:  python -m nflbets.weekly                # next week with posted lines
      python -m nflbets.weekly --week 3      # a specific week
      python -m nflbets.weekly --all         # every upcoming game with a line
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from . import data, strategy
from .config import Config
from .elo import EloModel
from .totals import TotalsModel

CARDS_DIR = Path(__file__).resolve().parent.parent / "cards"


def build_models(cfg: Config, games: pd.DataFrame) -> tuple[EloModel, TotalsModel]:
    """Replay all completed games chronologically to get current ratings."""
    elo, tot = EloModel(cfg), TotalsModel(cfg)
    for row in data.completed(games).itertuples(index=False):
        elo.update(row.season, row.home_team, row.away_team, row.result,
                   row.neutral, row.home_rest, row.away_rest, row.playoff,
                   row.home_qb_change, row.away_qb_change)
        tot.update(row.season, row.home_team, row.away_team,
                   row.home_score, row.away_score)
    return elo, tot


def card_rows(cfg: Config, games: pd.DataFrame, slate: pd.DataFrame) -> list[dict]:
    elo, tot = build_models(cfg, games)
    rows = []
    for row in slate.itertuples(index=False):
        _, pred_margin, _ = elo.pregame(
            row.season, row.home_team, row.away_team, row.neutral,
            row.home_rest, row.away_rest, row.playoff,
            row.home_qb_change, row.away_qb_change,
        )
        pred_total = tot.pregame(row.season, row.home_team, row.away_team)
        cands = strategy.candidates(cfg, row, pred_margin, pred_total)
        best, tier = strategy.best_bet(cfg, cands)
        anch_m, anch_t = strategy.anchored(cfg, row, pred_margin, pred_total)
        total_txt = f"{row.total_line:g}" if pd.notna(row.total_line) else "—"
        rows.append({
            "date": str(row.gameday.date()),
            "matchup": f"{row.away_team} @ {row.home_team}",
            "market": f"{row.home_team} {-row.spread_line:+g} / {total_txt}",
            "model_margin": anch_m,
            "model_total": anch_t,
            "raw_edge": pred_margin - row.spread_line,
            "best_bet": best.label() if best else "-",
            "tier": tier,
            "p_win": best.p_win if best else float("nan"),
            "ev": best.ev if best else float("nan"),
            "stake_pct": 100 * best.stake if best else 0.0,
        })
    return rows


def to_markdown(rows: list[dict], season: int, title: str) -> str:
    lines = [
        f"# {title}",
        "",
        "Auto-generated by `python -m nflbets.weekly` using the tuned champion "
        "config. Market column shows the current posted line (home spread / total).",
        "",
        "> Tiers: **STRONG** = calibrated EV clears the tuned threshold (rare; "
        "requires a very large model/market gap). **LEAN** = the best positive-EV "
        "option if you insist on betting the game. **PASS** = the model finds no "
        "positive-EV bet; the posted line is fair. Probabilities are calibrated "
        "on 2008-2019; see backtest-report.md for why expectations should be "
        "modest. Lines move - re-verify at your book.",
        "",
        "| Date | Matchup | Market (home) | Model margin | Model total | Raw edge | Best bet | Tier | P(win) | EV | Stake |",
        "|------|---------|---------------|--------------|-------------|----------|----------|------|--------|----|-------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['date']} | {r['matchup']} | {r['market']} | "
            f"{r['model_margin']:+.1f} | {r['model_total']:.1f} | "
            f"{r['raw_edge']:+.1f} | "
            f"{r['best_bet']} | {r['tier']} | {r['p_win']:.1%} | "
            f"{r['ev']:+.3f} | {r['stake_pct']:.2f}% |"
        )
    strong = [r for r in rows if r["tier"] == "STRONG"]
    lines += ["", f"**STRONG plays this card: {len(strong)}**"]
    for r in strong:
        lines.append(f"- {r['matchup']}: **{r['best_bet']}** "
                     f"(EV {r['ev']:+.3f}, stake {r['stake_pct']:.2f}%)")
    lines += ["", "_Model margin is quoted as home-team margin; positive favors "
              "the home team. Raw model/market gaps below ~6 points are noise._", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the weekly best-bet card")
    ap.add_argument("--season", type=int, default=None)
    ap.add_argument("--week", type=int, default=None)
    ap.add_argument("--all", action="store_true",
                    help="every upcoming game with a posted line")
    ap.add_argument("--refresh-hours", type=float, default=6.0,
                    help="re-download data if the local copy is older than this")
    args = ap.parse_args()

    cfg = Config.load()
    games = data.load(refresh_hours=args.refresh_hours)
    season = args.season or int(games.season.max())
    up = data.upcoming(games, season)
    if up.empty:
        print(f"No upcoming {season} games with posted lines.")
        return

    if not args.all:
        week = args.week or int(up.week.min())
        up = up[up.week == week]
        title = f"{season} Week {week} - Model Card"
        out = CARDS_DIR / f"{season}_wk{week:02d}.md"
    else:
        title = f"{season} - All Posted Lines - Model Card"
        out = CARDS_DIR / f"{season}_all.md"

    rows = card_rows(cfg, games, up)
    md = to_markdown(rows, season, title)
    CARDS_DIR.mkdir(exist_ok=True)
    out.write_text(md)
    print(md)
    print(f"[saved] {out}")


if __name__ == "__main__":
    main()
